spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cache
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true